### ISSUE TITLE
Meeting 2018-11-28

### ISSUE THREAD

**Issue by Centril** [rust-lang-nursery/wg-grammar#15]
Summary for today's meeting

- @eddyb#0426  had nothing to report since no progress has been made
- @centril#2862  worked on an RFC https://github.com/rust-lang/rfcs/pull/2602 and tested out the GLL syntax, it felt good, <https://github.com/Centril/rfcs/blob/rfc/attributes-galore/text/0000-attributes-galore.md#grammar> particularly with the `Rule |= Additions;` formatting. @qmx#4460  agreed it was pleasant and that it was "BNF done right".
- We call the notation in GLL: "lyg".
  - [x] Change file ending to `.lyg` after merging PR.
- @centril#2862 felt that parameterized grammars could reduce some duplication with e.g. `Bounds<P> = elems:P* % "+" "+"?;` and similar things.
- [ ] Cargo features should be tried out for nightly features
- [ ] @qmx#4460  needs to: "setup the initial test harness with rust-lang/rust vendored into the grammar repo as a submodule"
- [ ] @eddyb#0426  needs to do some stuff on the GLL side;
- [ ] @qmx#4460  will work on adding `%%` to GLL
- [ ] Test harness is top prio;
- [x] @centril#2862  will work on improving @eddyb#0426's PR wrt. style and such things.
- [ ] @ehus might split some work with @qmx.
